import { getUserPreferences } from "@/utils/user-preferences/server";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
	ClientHintsCheck,
	ThemeSelector,
	UserPreferencesProvider,
} from "@/utils/user-preferences/client";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const userPreferences = getUserPreferences();
	const theme = userPreferences.theme || userPreferences.prefersColorScheme;

	return (
		<UserPreferencesProvider userPreferences={userPreferences}>
			<html lang="en">
				<head>
					<ClientHintsCheck />
				</head>
				<body
					className={cn(
						inter.className,
						theme,
						"grid items-center justify-center gap-y-6 md:px-0 px-2",
					)}
				>
					<nav className="inline-flex items-center justify-end py-2">
						<ThemeSelector key={userPreferences.theme} />
					</nav>

					<main className="space-y-6 max-w-md">{children}</main>
				</body>
			</html>
		</UserPreferencesProvider>
	);
}
